name: QBanHammers
version: '2.4'
main: me.Qssaf.qbanhammer.QBanHammers
api-version: '1.21'
load: STARTUP
authors: [ Qssaf ]
description: "A staff utility plugin made for punishing players and more!"

commands:
  qbanhammer:
    description: "This is a command"
    usage: "/qbanhammer <arg>"
    aliases: [bh, banhammer, qbh]
    permission: qbanhammer.use
    permission-message: "You do not have permission to use this command"
permissions:
    qbanhammer.admin:
        description: "Allows the use of all Qbanhammer commands"
        default: op
        children:
            - qbanhammer.reload
            - qbanhammer.use
            - qbanhammer.gethammer
            - qbanhammer.togglegamecrasher
    qbanhammer.reload:
        description: "Allows the use of the Qbanhammer reload command"
        default: op
    qbanhammer.use:
        description: "Allows the use of the Qbanhammer command"
        default: op
    qbanhammer.gethammer:
        description: "Allows the use of the Qbanhammer gethammer command"
        default: op
    qbanhammer.togglegamecrasher:
        description: "Allows the use of the Qbanhammer toggle game crasher command"
        default: op
