name: Qbanhammer
version: '1.0'
main: me.Qssaf.qbanhammer.Qbanhammer
api-version: '1.21'
load: STARTUP
authors: [ Qssaf ]
description: "This plugin is made to make a banhammer"
commands:
  qbanhammer:
    description: "This is a command"
    usage: "/qbanhammer <arg>"
    aliases: [bh, banhammer, qbh]
    permission: qbanhammer.use
    permission-message: "You do not have permission to use this command"
permissions:
  qbanhammer.*:
    children:
      - qbanhammer.use
      - qbanhammer.kickhammer
      - qbanhammer.cheatinghammer
      - qbanhammer.xrayhammer
      - qbanhammer.permahammer
    default:  op
  qbanhammer.use:
    description: "Allows the use of the qbanhammer command"
    default: op
  qbanhammer.kickhammer:
    default: op
  qbanhammer.cheatinghammer:
    default: op
  qbanhammer.xrayhammer:
    default: op
  qbanhammer.permahammer:
    default: op
  qbanhammer.reload:
    default: op
    description: "Allows the use of the /qbanhammer reload command"
