name: Qbanhammer
version: '1.0'
main: me.Qssaf.qbanhammer.Qbanhammer
api-version: '1.21'
load: STARTUP
authors: [ Qssaf ]
description: "This plugin is made to make a banhammer"
commands:
  qbanhammer:
    description: "This is a command"
    usage: "/qbanhammer <arg>"
    aliases: [bh, banhammer, qbh]
    permission: qbanhammer.use
    permission-message: "You do not have permission to use this command"
permissions:
    qbanhammer.admin:
        description: "Allows the use of all Qbanhammer commands"
        default: op
        children:
            - qbanhammer.reload
            - qbanhammer.use
    qbanhammer.reload:
        description: "Allows the use of the Qbanhammer reload command"
        default: op
    qbanhammer.use:
        description: "Allows the use of the Qbanhammer command"
        default: op


