name: QBanHammers
version: '2.4'
main: me.Qssaf.qbanhammer.QBanHammers
api-version: '1.21'
load: STARTUP
authors: [ Qssaf ]
description: "A staff utility plugin made for punishing players and more!"

commands:
  qbanhammers:
    description: "This is a command"
    usage: "/qbanhammers <arg>"
    aliases: [bh, banhammers, qbh]
    permission: qbanhammers.use
    permission-message: "You do not have permission to use this command"
permissions:
    qbanhammers.admin:
        description: "Allows the use of all Qbanhammers commands"
        default: op
        children:
            - qbanhammers.reload
            - qbanhammers.use
            - qbanhammers.gethammer
            - qbanhammers.togglegamecrasher
    qbanhammers.reload:
        description: "Allows the use of the Qbanhammers reload command"
        default: op
    qbanhammers.use:
        description: "Allows the use of the Qbanhammers command"
        default: op
    qbanhammers.gethammer:
        description: "Allows the use of the Qbanhammers gethammer command"
        default: op
    qbanhammers.togglegamecrasher:
        description: "Allows the use of the Qbanhammers toggle game crasher option"
        default: op
